apiVersion: v1
kind: Pod
metadata:
  name: db-api
  labels:
    app: db-api
spec:
  containers:
    - name: db-api
      image: mysql
      ports: 
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap
