apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api-deployment
  labels:
    app: db-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
      - name: db-api
        image: mysql
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: db-configmap

