apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-node-deployment
  labels:
    app: api-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-node
  template:
    metadata:
      labels:
        app: api-node
    spec:
      containers:
      - name: api-node
        image: dancairo/app-users:v3
        ports:
        - containerPort: 2000
        envFrom:
        - configMapRef:
            name: sistema-configmap

